name: Troll Whelp
type: Troll Whelp
health: 36
moves: 5
image: res://units/images/trolls/whelp.png
attack:
  name: fist
  type: impact
  range: melee
  damage: 8
  number: 2
resistances:
  blade: 80
  pierce: 80
  impact: 100
  fire: 100
  cold: 100
  arcane: 110