name: "Sample Map"
id: "sample_map"
map_data: "res://maps/testMap.map"
turns: 30
sides: 
  - {
    side: 1,
    type: "Elvish Fighter",
    position: {x: 10, z: 1},
    gold: 100,
    income: 2,
    recruit: "Elvish Fighter, Elvish Archer, Elvish Scout, Elvish Shaman"
  }
  - {
    side: 2,
    type: "Orcish Grunt",
    position: {x: 10, z: 14},
    gold: 100,
    income: 2,
    recruit: "Orcish Archer, Orcish Assassin, Orcish Grunt, Troll Whelp"
  }
