name: Orcish Archer
type: Orcish Archer
health: 36
moves: 5
image: res://units/images/orcs/archer.png
attack:
  name: bow
  type: pierce
  distance: ranged
  damage: 6
  number: 3
resistances:
  blade: 100
  pierce: 100
  impact: 100
  fire: 100
  cold: 100
  arcane: 100