name: Orcish Assassin
type: Orcish Assassin
health: 26
moves: 6
image: res://units/images/orcs/assassin.png
attack:
  name: throwing knives
  type: blade
  range: ranged
  damage: 3
  number: 3
resistance:
  blade: 130
  pierce: 120
  impact: 120
  fire: 100
  cold: 100
  arcane: 100