name: Orcish Assassin
id: Orcish Assassin
level: 1
health: 26
moves: 6
experience: 34
image: res://units/images/orcs/assassin.png

attack:
  name: throwing knives
  type: blade
  range: ranged
  damage: 3
  strikes: 3

resistance:
  blade: 130
  pierce: 120
  impact: 120
  fire: 100
  cold: 100
  arcane: 100

defense:
  flat: 60
  forest: 70
  hills: 70
  mountains: 70
  village: 70

movement:
  flat: 1
  forest: 2
  hills: 1
  mountains: 2
  village: 1