name: Orcish Assassin
type: Orcish Assassin
health: 36
moves: 5
image: res://units/images/orcs/assassin.png
attack:
  name: throwing knives
  type: blade
  distance: ranged
  damage: 3
  number: 3
resistances:
  blade: 100
  pierce: 100
  impact: 100
  fire: 100
  cold: 100
  arcane: 100