name: Orcish Grunt
type: Orcish Grunt
health: 38
moves: 5
image: res://units/images/orcs/grunt.png
attack:
  name: sword
  type: blade
  range: melee
  damage: 9
  number: 2
resistance:
  blade: 100
  pierce: 100
  impact: 100
  fire: 100
  cold: 100
  arcane: 100