name: Orcish Grunt
type: Orcish Grunt
health: 38
moves: 5
image: res://units/images/orcs/grunt.png

attack:
  name: sword
  type: blade
  range: melee
  damage: 9
  strikes: 2

resistance:
  blade: 100
  pierce: 100
  impact: 100
  fire: 100
  cold: 100
  arcane: 100

defense:
  flat: 40
  forest: 50
  hills: 50
  mountains: 60
  village: 60

movement:
  flat: 1
  forest: 2
  hills: 1
  mountains: 2
  village: 1