name: Elvish Archer
type: Elvish Archer
health: 36
moves: 5
image: res://units/images/elves-wood/archer.png
attack:
  name: bow
  type: pierce
  range: ranged
  damage: 5
  number: 4
resistances:
  blade: 100
  pierce: 100
  impact: 100
  fire: 100
  cold: 100
  arcane: 110
