name: Elvish Scout
type: Elvish Scout
health: 32
moves: 9
image: res://units/images/elves-wood/scout.png

attack:
  name: sword
  type: blade
  range: melee
  damage: 4
  number: 3

resistance:
  blade: 100
  pierce: 120
  impact: 100
  fire: 100
  cold: 100
  arcane: 110

defense:
  flat: 40
  forest: 60
  hills: 50
  mountains: 60
  village: 40

movement:
  flat: 1
  forest: 1
  hills: 2
  mountains: 3
  village: 1