name: Elvish Scout
type: Elvish Scout
health: 32
moves: 9
image: res://units/images/elves-wood/scout.png
attack:
  name: sword
  type: blade
  range: melee
  damage: 4
  number: 3
resistances:
  blade: 100
  pierce: 120
  impact: 100
  fire: 100
  cold: 100
  arcane: 110