name: Elvish Shaman
type: Elvish Shaman
health: 36
moves: 5
image: res://units/images/elves-wood/shaman.png
attack:
  name: staff
  type: impact
  range: melee
  damage: 3
  number: 2
resistances:
  blade: 100
  pierce: 100
  impact: 100
  fire: 100
  cold: 100
  arcane: 110